title: FishWhere
description: Your Ultimate Fishing Companion
baseurl: "/FishWhereWebsite"
url: "https://hungerv.github.io"

# 多语言设置
languages: ["en", "zh"]
default_lang: "en"

# 构建设置
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github

# 其他设置
permalink: /:lang/:title/
relative_links:
  baseurl: true

# 静态文件处理
include:
  - assets
  - assets/css
  - assets/css/style.css 